import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ style: "normal", weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="flex  flex-col items-center">
          <main
            style={{
              backgroundImage: "linear-gradient(153deg, #712bda, #a45deb 100%)",
            }}
            className="min-h-screen w-full sm:w-96 "
          >
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
